# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence

cache:
  key: venv
  paths:
    - .venv

stages:
  - lint
  - build
  - test
  - push

format:
  stage: lint
  image: python:3-slim
  variables:
    POETRY_VIRTUALENVS_IN_PROJECT: "true"
  before_script:
    - apt update && apt install make
    - pip install poetry
    - poetry install
  script:
    - make format-check

type-check:
  stage: lint
  image: python:3-slim
  variables:
    POETRY_VIRTUALENVS_IN_PROJECT: "true"
  before_script:
    - apt update && apt install make
    - pip install poetry
    - poetry install
  script:
    - make type-check
  cache:
    key: check-cache
    paths:
      - .mypy_cache

build:
  stage: build
  image: python:3-slim
  variables:
    POETRY_VIRTUALENVS_IN_PROJECT: "true"
  before_script:
    - pip install poetry
    - poetry install
  script:
    - poetry build

docker:
  stage: push
  image: docker:20.10.10
  services:
    - docker:20.10.10-dind
  script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
    - docker pull $CI_REGISTRY_IMAGE:latest || true
    - docker build --cache-from $CI_REGISTRY_IMAGE:latest --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME --tag $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
    - docker push $CI_REGISTRY_IMAGE:latest
  only:
    - /^(\d+\.)?(\d+\.)?(\*|\d+)$/
  except:
    - branches

sast:
  stage: test
include:
  - template: Security/SAST.gitlab-ci.yml
