version: '3.1'
services:
  
  bot:
    build:
      context: .
    user: root
    environment:
      TELEGRAM_API_TOKEN:
      AWS_ACCESS_KEY_ID: XXX
      AWS_SECRET_ACCESS_KEY: XXX
      AWS_DEFAULT_REGION: us-east-1
      LOCALSTACK_ENDPOINT: http://localstack:4566
      DYNAMO_AES_ENCRYPTION_KEY: '4YY5yXS6nUrS8Z/6lDNGAg=='
      DYNAMO_AES_SIGN_KEY: '6PjwVFTXQqt1xbNrgxqJyg=='
    depends_on:
      localstack:
        condition: service_healthy
  
  localstack:
    image: localstack/localstack:latest
    environment:
      SERVICES: dynamodb,sts
    ports:
      - 4566:4566
    volumes:
      - ./localstack-setup.sh:/etc/localstack/init/ready.d/script.sh
    healthcheck:
      test: ["CMD", "bash", "-c", "awslocal dynamodb list-tables | grep -q yaotpbot-table"]
      start_period: 5s
