apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: yaotpbot
  name: yaotpbot
  namespace: yaotpbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yaotpbot
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: yaotpbot
    spec:
      containers:
      - env:
        - name: AWS_DEFAULT_REGION
          value: eu-central-1
        envFrom:
        - secretRef:
            name: yaotpbot-tokens
        image: registry.gitlab.com/ollaww/yaotpbot:0.0.12
        name: main
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 50m
            memory: 64Mi
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  labels:
    app: yaotpbot
  name: yaotpbot-tokens
  namespace: yaotpbot
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgBtajoxbtGy0Btj4GacG1Z6QCKQ9XoVouOBqSq+TsTd5X8OX+wqMDBTj/gwsLzkfDdNlMg4e0q3julYREfAlXX1yjWmbdhvZLNoeohVWPPNr2aLHzm1AFEPXo7XKjma+05ICGuTw6CIYUzKhBWm8S8S91MieENKplT8qfAV+KjjIv+YXHQO6UUiThNvIUACPznheXGbZZJo3/DAVsRp26Jl195YdRR0cm6h8im0iQsIv3K4I7UyuRmp2GmUTtUC9JUTm6J3oydykhP4nEX8Pa3/xEHjZc1edFM1L4b8opovpBZN41kNF1aL0Y6lh62nDYhapSowwjIYuvV2VeF9vheVeCQkDCYf8uSuwqgsdZonjTAKQB/u8U6HrASQTC7d8l4xUDW7hq2XYEIwwlRWt5UEvuJreZrNiQVU2QkmZ3LqugfiEZWGCSmQMNQWmAx5MzpIY7af/lfPbj9OX8iKL9iODybHfGU7BIEaYRgiKeXMg91GOMgXdjDcCD1vI59WTeXh6L0tt04gPez5y+73tR4vhu3qwxZV3+ptmrbjh09YUzwuAxhXdrqxAo0It6KX+Pl3sX5ODXT//53wwXM0KbGhj47XA99IoRvxHhWvLvMefKlVfU1EYuFK3mLudQViAfXljMthRY4KZ3KzGKRnPlbf4ej8SIR8JUIE76V2ugU927zHq1HNupKAdunKyJ9lE8LTAJWip8iHo1sPOFCvm5rmKpE8Aw==
    AWS_SECRET_ACCESS_KEY: AgBThICOb3C6IO5uo4zMwZKwwPhlEfr4WURsTlRTgCVaR/gQb2QgdLZlWExTDHRWefiUajAnF6PNXJjbtWh+PY1QWBuSD2PTfblhNICbG31jgXEU1sitVBWj3o7KEaMbLdFTx8k3ktitLUnRWchEpg2+TfJwXLDIRBKBGmX0qo3uM5otegcuhiTINHSFhrOCUG+Q0dSba9ei5pDSj64IEqDIcVxcgSRXcxeQ3+Tp0H4XjyHBjSzFCokGNluDgyISaH2eAAN8TOlwmJ2Ajw2SjJUQGovCxcREg06ZJZ+9SX5Ns/V2wOB4ThErqyFU28N+FPrhWhO3KX8EzfTJdU3B7PYjCwaJF2taxmj29K8VuJzhqAR+jS3ukCRZ1r1+OwA9YBj30u/U7fxq/UJJoI/WgSVt8AsIYiIv3GxIFuSYBertClvZ8qFyKvWVVWenHuYiRXUw4r/tyB9h4covTLK/Fm1a9mhPV5GoGquJ9bJ7y5Rj1AbsiShOJKdUEl7zU9ywARv6K6RkUcwBUi2Rs+xL//jf+CM6RW7V+8easUdKOzmnATYYO33BnIIffFLyCdBeIfqkqOyUxLMnB+TZGeH+p8k5VT/bjiZqCwZp1En4HGf+hM6jOWqvwM+JjwrWwis1swbKzn6CogLdDD+ve7VJmHzzSFVWWK1ToEoPihOVxkTv5RROIBGmN/9ZNDrfhG8ltx8wrfJ3jM7Zg/ZF+1/MbFExDEEcCCOcCzjZXLMlJhwkdkiRjGfHXh3G
    DYNAMO_AES_ENCRYPTION_KEY: AgB3Ky8cxinBhT4mwvDAKX383Rnr/1OJZBx5+PCblNByG6gzKGtgJnISJwEavsB0LSZz8PlDocE/2M9SY9JxKXovXmZXDNElPlE25F0McDthVUqKh+X+jmuAL/8G9uMIg3ZOx37OEySBTcucjyUrR9Xd8TpvXAzftMI8l44opOLB3fjscCbk1Or8FppBt+3KdRdF+j9fwrxOdiaZnYkl40F74GsjSQqzFaQIpJPj0ijuMy26g2LHS6a5mdeCAiLtKBU5yNRlJ/4J5cx71jsE5nWby1qDxC+e7lwIMX/zxxUTyHOmgvWzK+obDtGuWGrMDzziKIshWjfQsfGIoJo4QmyK+o67uwOJWbyxMNcTZNlh7YqbuuUxhpIAkn60bwIPudRbeOtu8DORWQi5+eZEupeV4USUwqJWWcvv12MxKjoT0HY/GJfr3u4yYzHf1Az/L0KPJD/SUb2El0ndAFW2O1o33Ooj2pyYyzQgMsNHX8s0wZ9NUm3aZjoX1PyiWxn9brsyE7KkREuXMCcmLzpEGHbxS6ZS+IRqHqCLOI8rCh5fF7tOVVPCMIJSIJX4llhQokwKtPiqZD5IvAYzHlmcOUAFh46dlafayaV+3HkN0RfZui2U96d7RNefALyjZW/NQcD5uNmLGRhhMIhKwm64BEGpJwCpHL3awwetk3gI8GeBF1WGXTTGfPbxmFT2WYrRPGMinhrKbIhaOTV268vqq1P4eTzfzU66IgM=
    DYNAMO_AES_SIGN_KEY: AgBnaSz/mzo0BMPyvFu34vPfJDj/qiJHnhTUNBGfxiBlrlHYlX6hxUl6/EKXULU9ngULEQpxClrYZ4n4HrmpY4fAQeogafXkJAYWRhAM2rl8+80Qb6/i1PrxFJiw67DWpTD/Di141DfqJD5PmDI+JQYlQWv1h7MKq+V9AsQ2j5DPAidycSDa5Wvx6NHQrrn9eZnAHL1p1renYsqbzXtOiILoc53P7HjI+RLcKX24SMxz7epL7DMyyBG5n+XIN820LL1AcCQJ+bh3T5xE2UvvLe0dmqxuNFSNIQhWs5zbqbpW44FXnmME2plTs+Z972Jqd+HvkuumcRS3nReNqT4nm5RAihYnT0yCJDTNCDc0q5VEcjq5o4NV+PLD6vd/hklHpNVM6RcehIhsYCQOcaBBcTgwONkakkxMWtfQhVcA8XsB4+z4QgJ1a0zu0aBI/kfFwxv//csgjKaenKSCwzNryB2y/CqSlXkzFrsYqTA2xkEwaAqUghsVEq6KzSsuDVTUnrQDP+jHbh8ZiSlL/xc+I5sjNVvyW8JeQS4Vk9W5IZaROUVMobZvgWS9aVTiMwRWBsJP4MezIKW7Th6jhUDyNSBUVEKYdj1s6Ento2Rlj93f3R7Fcy0Nv2yIjn3OmLBVZOjv6OyKmkVz1G/AmBKyc9PY4y/vXvNFbGkW+OB4FEjISZRmpEir+CGOvsp3vvUvpswtaQAfPSTN4GIxQyI1le8NGSyuw9hmJ3Q=
    TELEGRAM_API_TOKEN: AgAswqzzyyKNhekvtLC6XjkOT0uysfzPtAXLypNQMRH9s/5j8MpFv1+FG4EgSwKaUmqOkK7DjkgjrMQOHtixP5FsZF9m8PTbvyo2h7bv9l6v6+f0Vcr5WTQz/76DIivTuD+cbLPu9aVgBPODFvLTFIzBnBwEbv/nSoFK8ywBIfMFlOcBnuxxnQIktgQmaOdonV8R8oSCOA8/AGkadhuV8kOcoUyV/snZTFjDIj3AF+LFxYN6F+R1vDJ03lUv0HelgVoM5KaLaEpTtTAu1J0ad3F2WPpR4geJQht64Isf4RUH3CQuDg2DG6jJZf0BYu6UvQSEvIuIR6YcEqZnE7pheRiHKVmYbbWJhIyezdawKlyPkNygJJ4cGUt7UyGfaQ1aKwenOjeuI9pq5lKAgy3S9HGpHRigNQvyTAVL0AvzPxoqIuERqTr7GO7b5KztZjbc2TcX9qmkS+ZtpZ9c5NDJJe/jFNO7sZ2NqTJQFGC16ZGyO6mEq9N2VYm/gE8glWD2KA/8IOuTsQxQCxoNfAyQErheNQDBzeKDcKu0xRn9HEuu+BaRHVs9UcNOtZqFrFgN/PlmeX9mxz7SKjcOSyUTeHD9hwl1u8KOFuMtQCOWIO6lCTFfl3EXbjOU2DA4qTTzMYKwJvu5pivofWIck+m+msXZhZ+iuVJ+nkzNtEcoL6vpY2am6i144/QYDdBPxnKj2f4wqlbo5Y9EZkRQqIG3f1xKo7LoFhlo8rGTTQuBQUHCkgB+RPRJzE/NBKibusOn
  template:
    metadata:
      creationTimestamp: null
      name: yaotpbot-tokens
      namespace: yaotpbot
    type: Opaque
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
    app: yaotpbot
  name: allow-all-egress
  namespace: yaotpbot
spec:
  podSelector:
    matchLabels:
      app: yaotpbot
  policyTypes:
  - Ingress
