apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: yaotpbot
  name: yaotpbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yaotpbot
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: yaotpbot
    spec:
      containers:
      - env:
        - name: AWS_DEFAULT_REGION
          value: eu-central-1
        envFrom:
        - secretRef:
            name: yaotpbot-tokens
        image: registry.gitlab.com/ollaww/yaotpbot:0.0.4
        name: main
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 256Mi
status: {}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: yaotpbot-tokens
  namespace: yaotpbot
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgARs9RT95XvnUNAXAETdfY8j03igf1ZuYEkD/S5hCVHlsIqXstHKLGdP+ulx9ImXihNIlQtdE+wBNtyZ+IWmsWDDWh8Z8tImOyuNGQ3wr7SFTideVPlat3ucG7Eoqc1OADnejRDfieTUDmV/BlcebOWusIwNpi+jXHANktQSUPIXgFrICEoRAXj3AreTFsm+uC0y1el/Do9Qs/PD897wcVSaON/QY8KW+1s2zcCB3gYU+zp4+UHbcsNRVyYqvc1wFJ8cLwiwDFSF4rOXkcT+45IvxLGPHNRNk2ja2L332HRadOsmqiC9n2fs1wFV7UNBLWPdUIkTYQRsLYobi4X8h/n+ToTKJJ05PgJ2IDqKkJrebFYVuk1/VIPIw2HVDquZ/xqAt2KLaQ8JTrEZmTBaVpm0GsGyQKGmrNkITSd5MUPptym7VaWIU/B27EZj24YUzKzRwuePnjv0YTBnDfrsgFJER/3zanTXBHV6A0UaV658g38w9Y8ZvgOsCycOQVt6KMVx9nxSfCeyBLhzKiMF+D5g3uQFgjlEsG3rok4oaShM1yfa/BLuDo01+1pzcymrKlEm7oRB1hoEOSfktX5kCaEiHVSpbdkLgSJrMMrH/sVzuvoKTBq++s3/fjKPFlXUa88pgrN+IJp5EQtBR/inieuA1aPueADEJ9mV0YhEPxJgX5wgS7G8ocN8Yh2ipg5AYwgIw8LO4dN8BQhglLoJLu68E8fag==
    AWS_SECRET_ACCESS_KEY: AgBBTPdHQ0w0bXaO4PmxUPEpTVE3wIIdLKkb6yG895mKif3JFrZB/lvZmM3X7G3UBvQrIONyGX6BaOlkxaPzF1OYYD7MfTO9CT9nPzRj9vXrApSy/nLxB7Y5BujvfvV7hPmnPg7x5MQgkmrop6Sk1P4lTs9S8A2Dfe4BsEj8id2DcrM9Ecovbgb0RYv3tiBM4S5HPYm7B2FourRTsjJGXVXoa79P11N/x7D6sDv4z/sMV4Wwiz9BNW+1nI0VUcPccy+Qau+Z0a9ngt0Vg6PcYakf4CyIgfPlMq5S3s23F3dKTVIDRc4ExKpcjoA6jv5CmYET6gSrqSFsJ8WWzSj1A6+XbPczMyvzyYnEw8tEXHkpxZKxC7CWvdXTP9eFUwrYRcsf2ZZwlwKRgC5e8vgrX/zTdcId+NyoyHQDUqD8ZcnGybfbGDmi8GO1SZXBOHZkbvdolqTU3vBtu5SjcOS6IHhVXj8jG2R4M7tCVV4LE8hKxWQjxDchXT7jLWJoVKFaX1MMif3xWTC6z7o8iSVAtwfBttJR3TZxPSI4D6zYWUqj9pqRP/dimfLyS+eDRyWV+tKmE7Avhl2aDsv/ZMmg5ksTziaAW4vcrM/h2sqduNfnJiwZR1GxqLGvZVOmyI9L/QAuD6LQhwCM82xVOqMbW9dRkx3EGZdHDM4QqVluv5c/WO4GIQ1N6NOcNjrM0bX9CBbS5xoFwNVFQDyOS1KGh/C3Lq+rlsrSAHlUfb7TO0XPIvt7tgEag+30
    DYNAMO_AES_ENCRYPTION_KEY: AgCll4uzr1iQBcnMiKKYPx7sjv++e1btpDrlJ/hQf/9DU30Tw3yurLrPd5gjZ0p/mYBiCK2WJevRN5X+cTT/u4+PwXpKvDhOmiCDH5g2sja2fjoKxxw0SvThu33KanhRWaGJqBwTJUC45Oaawz9dLfeJWpKXJQ85r3WIDUUqNFiN0Xe3NsraY9KqdFQLRliTVqG937vaLdarLjySS/yW0u5+Q7/2GRDsktmTzexKQZedgMCACLpt+bVEX3nzLBwyRv+Z5V4Mg/9zMCkCyyVLQ/gU2csffEyVKzcfSTmyq0oNawo9WWyZHoFcBsJCMFVcyoFsiOLfCd0WAFWVMf6u69q9wxy636QYnoys7Zg3d58QoipSVdOogmOcDzmj1bT7aKd5yrjZijgbtceAMOsLXYSsE3C7xebyHaZnCLW6Xq3/jDjjqZ42fOhP8HNa5v/o3Ug0eYP38qGvn1xhVn8BIOs80xEwgjErVqruzfc2oPjTamfd0ykw90SZt4+DaBqtdUbV7aVfUt3wME7ptRhAEx/DnIWG1wOhhlD1Ja7A6XGBNnG3W+/eqcJkcVGKvr6OroTPQ4Nk38NuJ304o17v4+jCmmoZsu75/fp441Ik+t0wrsbPKbiCBDsrV8UynjaT2nszoYBuM+c7OxiuzP3LvHbHV0Ha7oDnjySA9R5PPkw/Hx4k4CS8vYUCybgkntV3JSD5cIBDpX5iJeZZUVsQ+WrNA2OWPblCh2Q=
    DYNAMO_AES_SIGN_KEY: AgAXtN5qhJsw28aqdKV5FUIFXnPlj0ihmEOl2uy5ilqMrWA6qac8q+NgqzXVhrsJAiALPhmSa19SP3W+nKsjRNU6fCKMLPqo3PX9ADSgnblc2ZPXLw+GIBygdqXY9URjBtZtB3zV1RAKvmySlj/qFn7sp6NRpJZQUKlupW3zlTd7pNVsuu+fLi6BwhLdhaNijB18LO9HlZGYPIC8F2cTz2eFnThP+Rlq3Uf0YKJm0ap9zTku0L0uhcRCKc/R8BtuKFKJSgZHAjtUd3Zcn/OllRRTNAEiCfyO0QLa7AHrL/EaM/g1L2dtsncFU7as7TXfwXJgWEI+gwN7YfqYbcfWjbPHjrLzk1UV+9safQqQQyGUMPKMAinLiBAYl94iKX/lL/QE7FF3TvDRzTVYe3XLOmgkeRUKUaXbHnHT8FVtLYYb3AxhJPlbtP+S1cKN4nwmQC/F45KrjyCaZjfB8e5HXwj78gYmOHQs+SknGvwDkQb716dWxuGADCIaaPts/cvdwTk/lyDN+qt/EYNT8PBFzs49VFrUEOkfsTPn/89FAhQkzU9/ykuX23IGwni+jcA15HIAk5QNQ7GmEqxKhN6tkdA1T8nUp0ZdOiFfbcGC3owjda79pHJVkrXrcG7Xd20Vi8WGIsPYSAmDixOv0CnTgrAoZQ3DcMxSt8FAtp40WrU6MNtmOTkOtnZplVA5RIGICj+RY9wEbXvJyGhf3jhpfFS+dTwWx04gIRM=
    TELEGRAM_API_TOKEN: AgAM6otheh2hIWRSjWA1FVRXQuI7pLDkhautcSa8WhWGLCwStW9BGSemvdNRsdVJ0PE+Rc6D49z7aM72wwy+ruc1E++JUvm+7d3LHHo66IYXsfJWWca1CXD55bfK+ybvh8Sf0TA4g8FGYSKLNc5QZznm/VscyvVtN+cTvjYEld+xonSrqrSvMGPnGY1b2BysTW9oKTidL/aFKYFXRzgtmjBWJ4bpaBzd3zqp7FTtyImUC4ZADgVoiO7VmiQi2O8yGgZAcrlCEbR4XdTgAQp4IRYAkGPibuvtL0Afbkg+j58uv0mwzLvpBBrE+cT9Z3YJaDmtIVNK+2gyJVnqG0fHOUQaMGc1Txo6BTUGKi6qWhIw21rME5oIOhFftLwspoRYxMZX3S/WE6Vj9InZVZChByj7oSjmvmETWAwA/NEmM2jz1knArK6avKUZEyNXawlz6YVb60rtV4ES042DrP8Rsbwcw7r1OvNk78SVa2mx2/0M1kSyKAj2sWVkunRz+IFzKFJKE1AFpaukdpZt3A2dtFL53ArypBZYXls+w++pUfeU+1Z/tM4ngutnBE+aiVHdkwZjgUha9LT4nqsYwGHtbtYf1dRKFGrkomgpypaUOux3xkNYB6Qml6vDrCfSWNSq4lPlqmZFzShra6UWfw5bYw6dRFtmGTUGQsfm7VRbi+lDV7iRNLPBOgc8M2awtItLn76lvTdDMk9SnoQEEfN22celfK50fHhQ6Gvysek0cCTA/aufGcOsDSgImUVCJ7lD
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: yaotpbot-tokens
      namespace: yaotpbot
