apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: yaotpbot
  name: yaotpbot
  namespace: yaotpbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yaotpbot
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: yaotpbot
    spec:
      containers:
      - env:
        - name: AWS_DEFAULT_REGION
          value: eu-central-1
        envFrom:
        - secretRef:
            name: yaotpbot-tokens
        image: registry.gitlab.com/ollaww/yaotpbot:0.0.9
        name: main
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 50m
            memory: 64Mi
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  labels:
    app: yaotpbot
  name: yaotpbot-tokens
  namespace: yaotpbot
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgBM54KK1Ut/v3uJHEiiSkmkM6BiVWaZVhPJp/IHPCbpgactgBMJ+WPCGWgSfMPxNUaLp1IYGWJU488FKqW7zAPc5s5Jq6vTXX8zvcVvbSvK68avJ05qkZXxjqjxDJxZIpZU0RXaNwWSG05slLN9ZiS+gbqYYdPc04H96QYsVCJHfPeUT9j8wZ1zlKFeqe+zn4ddNAGrH0yKag5SAtcZd1ruyRNgkLL0CzEmo/UtXPcdxPm28lIoWx3R0fQiIc2e+fxXw048B7sJtA3XoGhLcKyUZtktnSZaxfgjWQpLyKi1Nrwr3JeY5FrRFAUoAJOiHDhD3SITaMx2Z6F6g0bXXLj7axoCWDqWQ5fj3tTFwAikemgE5/5qv+SkKhNNmnilccPZ4F9cWTyKZdYY5VG19jxSVLl6AtW07azVOAYnZqRwIerY6bKlQSsq5xV/MXPo/l6R9sfETE88euRCOl2j/OupJYOLxDWy41If8WRlRw+sa4292LbOxIGGm9FqfSTxxlo7fZVeJIxXu8TUqTMkq9fkvBKQWFg/cGl6CGZXX3JX9/hrkh9FYllgBNzB1qnHHmkKPPg+vo+ax6pcn2lr8Nxj5WabRYqPEhNirfWMG/CtceY4WaP+9ytMng3I/k2swaS86WgC5I3EwDFgmS5Oec1ASOuLJ4tZ12Z5MROFp589BDk4qNs5vwOmcDxKMC3U2RyPIEBHBxayoDKZLOH8mb+lJ5l62Q==
    AWS_SECRET_ACCESS_KEY: AgBLef/JE3axyR7XB/4lgizWo3UabSnVYjwCVB0Hm/shstrXee/spHs7jS3nFfxRIgcmBOb62USm/hI2XinWGTgM/mjS618nbNu0YOQHyBR1OelTaz6GZcvMLdAh224gFogsAnTWGuh+bAaJR3TIOHCtW+ivB2pNf556VGo55JD3xzgWjRM+FNRk+GXAltpQQFqDDO6fi0EQtGdTR90juwWLEKXW140TFVJX2jhI7b97UeNE+OAJOyQ2UkjRnd4/P1pkqMgkOtKPw/aGtpyU+atMD9JYXX9kBtinxSf6tcDMcxeYtlOwhJHi9nHgQMucL0k0QSE2UNIQk3/HflJtIJDmYWYGv5Y+LeZ5H4jUMMrMx9VNLP0MIWKVtdjuVsP/fW+HV4lM9C+5bLaX9n6skbw/fw678w3gsrnK1EtlIpSqPSEfhRVBbNfQaX/YM2amGy4Y/KkLLCB8tsq0pNP8OEblahGSLG6YUgEt/94J8GuwBajClrRpPVXGueCQTjf3wJ8MeMLX4Ec51O6dv2bfIDjIB8aDzRLqXDrUKDsvlmlortp6GFqF71zkkHzix/jNEI6Hbc1ymckQXV/d10Bl7JXvZbXtKb7idPJNqunURpCPkcTWdqMRa6IpyPZc5JXaJJi6+y9ZQUu5YlIRrcDYPRodN6WnHkcVB24IkC5cX7EbuKvg6DnGr3gM19bRMbHyjp7q4GJkv/mR25OeMf9zxPSUxko6JHQwMMx0jrR4aCQ3XgmEPEV/PvYJ
    DYNAMO_AES_ENCRYPTION_KEY: AgB0uYWlVnjd+sLY8X6dWOeex6Kkpd12vQFY6eZbosgDmNDzFCAfXzzwD7EM1te7W8RvY9xuADy9dbuR9tadXXsmHu/sbbz+cc78tyXuwsdrtZ+IuyXwCR0mzEjchPTXFacpbVwcHVFCl9mLSnavVZNffULNl6EdbhHq4FThDkatIy+8pM1/tyeehvwH5osmFTTIN0y2OmAAVtRGHPGHzBa/GywDKw+CJtVHr/flNcKTMxQP0UbwNSWjpyWn4/qLmKu3ydDWlMWLJuyLcYZI2YyCwITo2D9ijabDl89UeQckbKkaeyMkTYDPFtNQjyB2aEOqiPOvW6c+2dqxr1lpWiVUGd6kRK7U4kjHr5OQr1AQlc6REJn0em3jOiquZDpQIOAz3pV2bNjgrVaCVzpwdfIIaAiWqO0OZL1DriNQOOoDqTvkFMIVZRJ5OEW8UFC9sjJPh+rvUH8+sWR7vnbFz7P1/T3/v3cUJ5gN+fhAIMg5cHaI4Ou+dW4nb8eZh8sy6aDqmufHQJI2MgFxuMMaLIGNotpc6SlzPY/Rfy5H4+Hbn7hdYhvuYte6WPyQMwi073vpqc7Aw0ce2Jj+oehj3OH9h4Jw6d2vPcAHtrdDDQcE5OZ2rseT/KkTPg8uPfeFYzfoAR6Rhtfg8xGHeG6va+EFQtMdzxi/rD5SRPdEXiSNUWBFQ445splp07vFcCKUDJzB17rhJQIPxdr9N1qvQ35AnXU86YgNenU=
    DYNAMO_AES_SIGN_KEY: AgC0Ab8Xlk7mo+Cv28eZ2+VuWrTZ0FFYblKOreQgarDo2K11O/wCCmaXXbGFXUwMR/LL19KNUNhUtqudlLDdbHTAg9G+Xl4NTSpdMeQdofaV/6VA6qZEn19phQ9DOjQGTJh3y2xs+PjjoEiw4dN2HZcc7aEqXhzZb3kgifoXC2f3v+qhqGgbixwOdi2mu4j1/9Sl54HXeftUgtgpmnb1xW1xbHf6G5LWWPhRtCwCBeisdJkU8p/QNQRz59GsKglrixoFeAUYtQHt9iEu379vq66rWOhSb5/FELMWyndtwXTbIng9dO9oMdVjUAzbiNPdLjh73omU0p2B+SVuegT5I+9JuPJ+xgz5UlpTL4Vn4hxg4sbwhu/RqQcsmAkfGXXPltOIq4pyYy4zmUKk4iuSBD8rhLzZf/EJsFT+DDszGNFSHS72RWXvXbCjFttx999mCMf36tbXwjnFshg8MfvrRQiu7ab9LyVPFR8KeRxEetUTRS7rtB0HPxvDO5K2xQf6KATY37l4a/NVo5f40MmuEic/TNPLVF8REOPm3pu1e2s+eoftlvGrEO6qLekkEToYKso3OmUI7Sls484Ma+jiYNo910tI5aeRHyi3puBGOGXhygr+Ql5V/FKNc4BHZDgPmBbRJug2Uw5RmtXhLyH5axyKThYsBboIvJ4QD3/N5hnVc9AApYt5zBWhXI8qGRMYzql+lzp4m1ympaKY8lUmICk8hK4NBQgCQ3c=
    TELEGRAM_API_TOKEN: AgAfZ4JEsvVIfX2DWAxsaWn5uQWjBvYstyZAJ9mtzs24pARUgzilclQ9JzAupKYdKpeIKZwbnsnY7bKrFl5gRhpCj2XClLETeVmI3gHS5psy3VpTq80Wy36bS23cEKUvBc17IgJqxaVhy6HCkM1TLWyKE8sXf7axEsdrxyJYGYxSUiB313tZii0m+ykO7Yks4nyn3kHDU/8QU5thZQydIJR9F+H+ufwQHfV8f/UWYld8Yllr7dRUbx9RU0BB4X14hbemBVhXeZPsFU3vMDhzMa65aFVCIThvXJpLLOvLvcxFx4w+pKhaU3HaGlkQtkSZW1GfGw5E68XQPYnBteuQKTe646jAAL8GwFDGB9IIYlucDX7MlZimNpUpSoP9La00yMnM8E2YylG6JQYdGvA/ClUP+UN5l0/3EfSV/n45Yns3dGzWDiQ5l9CURIXepkAXNsR3c8mJd+FZty9g97v3uvl8mhCw8Wz9C5cTC6TDJUqkhTbQlpKtFiIlLFF8OYa4tBayFlF2PVfMQtLqjS3hdNc5dkX8yztitGGPIG0LRT3rXuubttZ5pgzXNTL9oXXEPBXJOW+Q36gELYd4Nu2GF7Gawb95bJGPNYVW/GQ2JNocgAfm7BsU9LGGn2FaiUvbbXmyhuabWaWk4y4BpVjqVeGy+p4Hg4X0XljtCZ8OV8v2r81+3CXRMopWvVfJ47Z/qAvTX/GPo0g7QqfNZf/fI7m6657xDjvv/hA5J/xyrM33ZLVEbujvTb+RDyDjck4J
  template:
    metadata:
      creationTimestamp: null
      name: yaotpbot-tokens
      namespace: yaotpbot
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
    app: yaotpbot
  name: allow-all-egress
  namespace: yaotpbot
spec:
  podSelector:
    matchLabels:
      app: yaotpbot
  policyTypes:
  - Ingress
