gitops:
  manifest_projects:
    - id: ollaww/yaotpbot
      default_namespace: yaotpbot
      paths:
        - glob: "/gitops-artitfacts/*.{yaml,yml}"
      reconcile_timeout: 3600s
      dry_run_strategy: none
      prune: true
      prune_timeout: 3600s
      prune_propagation_policy: foreground
      inventory_policy: must_match
