apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: yaotpbot
  name: yaotpbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yaotpbot
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: yaotpbot
    spec:
      containers:
      - image: registry.gitlab.com/ollaww/yaotpbot:0.0.2
        name: main
        resources: {}
status: {}
